/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Grafo;

/**
 *
 * @author Gloria
 */
public class BuscarTodasLasPalabras extends javax.swing.JFrame {
    public static Grafo grafo;
    public static String[] diccionario;
    public static char[][] tablero;
    public static Cargar ventanaCargarOriginal;
    
    /**
     * Creates new form BuscarTodasLasPalabras
     */
    public BuscarTodasLasPalabras(Grafo g, String[] dict, char[][] tab, Cargar v1) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        BuscarTodasLasPalabras.grafo = g; 
        BuscarTodasLasPalabras.diccionario = dict;
        BuscarTodasLasPalabras.tablero = tab;
        BuscarTodasLasPalabras.ventanaCargarOriginal = v1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelTitulo = new javax.swing.JLabel();
        jScrollPaneResultados = new javax.swing.JScrollPane();
        textAreaResultados = new javax.swing.JTextArea();
        jLabelTiempo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabelTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        JLabelTitulo.setText("Palabras Encontradas");
        getContentPane().add(JLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        textAreaResultados.setEditable(false);
        textAreaResultados.setColumns(20);
        textAreaResultados.setRows(5);
        jScrollPaneResultados.setViewportView(textAreaResultados);

        getContentPane().add(jScrollPaneResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 110));

        jLabelTiempo.setText("Tiempo de busqueda");
        getContentPane().add(jLabelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jButton1.setText("DFS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jButton2.setText("BFS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
      
        this.setVisible(false);
        Menu menuNuevo = new Menu(this.ventanaCargarOriginal);
        menuNuevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("DEBUG (BuscarTodasLasPalabras): Iniciando búsqueda de todas las palabras (DFS).");
        textAreaResultados.setText("Buscando palabras...\n");

        if (BuscarTodasLasPalabras.grafo == null || BuscarTodasLasPalabras.diccionario == null || BuscarTodasLasPalabras.diccionario.length == 0) {
            String errorMsg = "ERROR (BuscarTodasLasPalabras): Datos incompletos para iniciar la búsqueda.\n"
                            + "Asegúrate de cargar el archivo correctamente desde el menú principal.";
            System.err.println(errorMsg);
            textAreaResultados.setText(errorMsg);
            jLabelTiempo.setText("Tiempo de búsqueda: Error de datos");
            return;
        }

        long startTime = System.currentTimeMillis();
        StringBuilder resultadosBuilder = new StringBuilder();

        
        String[] palabrasEncontradasArray = new String[200]; 
        int palabrasEncontradasCount = 0; 
        
        int rows = 4;
        int cols = 4;

        for (int i = 0; i < diccionario.length; i++) {
            String palabra = diccionario[i]; 
            if (palabra == null || palabra.trim().isEmpty()) {
                continue;
            }
            palabra = palabra.trim().toUpperCase();

            if (palabra.length() < 3) {
                System.out.println("DEBUG (BuscarTodasLasPalabras): Palabra '" + palabra + "' ignorada, menos de 3 letras.");
                continue;
            }

          
            boolean alreadyFound = false;
            for (int k = 0; k < palabrasEncontradasCount; k++) {
              
                if (palabrasEncontradasArray[k] != null && palabrasEncontradasArray[k].equals(palabra)) {
                    alreadyFound = true;
                    break;
                }
            }
            if (alreadyFound) {
                System.out.println("DEBUG (BuscarTodasLasPalabras): Palabra '" + palabra + "' ya encontrada, saltando.");
                continue; 
            }

            System.out.println("DEBUG (BuscarTodasLasPalabras): Buscando palabra: " + palabra);

            boolean foundCurrentWordInBoard = false; 
            for (int r = 0; r < rows; r++) {
                for (int c = 0; c < cols; c++) {
                    boolean[][] visited = new boolean[rows][cols];

                    if (grafo.buscarPalabraEnCelda(palabra, r, c, visited, 0)) {
                      
                        if (palabrasEncontradasCount < palabrasEncontradasArray.length) {
                            palabrasEncontradasArray[palabrasEncontradasCount] = palabra;
                            palabrasEncontradasCount++;
                        } else {
                            System.err.println("Advertencia: El arreglo de palabras encontradas está lleno. No se pueden almacenar más palabras.");
                          
                        }
                        foundCurrentWordInBoard = true;
                        System.out.println("DEBUG (BuscarTodasLasPalabras): Palabra encontrada: " + palabra);
                        break; 
                    }
                }
                if (foundCurrentWordInBoard) {
                    break; 
                }
            }
        }

        long endTime = System.currentTimeMillis();
        long duration = endTime - startTime;

       
        if (palabrasEncontradasCount == 0) {
            textAreaResultados.setText("No se encontraron palabras del diccionario en la sopa de letras.");
        } else {
            resultadosBuilder.append("Palabras encontradas (").append(palabrasEncontradasCount).append("):\n");
            for (int k = 0; k < palabrasEncontradasCount; k++) {
                resultadosBuilder.append("- ").append(palabrasEncontradasArray[k]).append("\n");
            }
            textAreaResultados.setText(resultadosBuilder.toString());
        }
        jLabelTiempo.setText("Tiempo de búsqueda: " + duration + " ms");

        System.out.println("DEBUG (BuscarTodasLasPalabras): Resultados finales:\n" + textAreaResultados.getText());
        System.out.println("DEBUG (BuscarTodasLasPalabras): Tiempo total de búsqueda: " + duration + " ms");
    
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarTodasLasPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarTodasLasPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarTodasLasPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarTodasLasPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarTodasLasPalabras(grafo, diccionario, tablero, ventanaCargarOriginal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelTitulo;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JScrollPane jScrollPaneResultados;
    private javax.swing.JTextArea textAreaResultados;
    // End of variables declaration//GEN-END:variables
}
