/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import EDD.Grafo;
import Interfaces.Cargar;

/**
 *
 * @author Gloria
 */
public class BuscarPalabraEsp extends javax.swing.JFrame {

    private Grafo grafo;
    private String[] diccionario;
    private char[][] tablero;
    private Cargar ventanaCargarOriginal; // Necesitas la clase Carga

    public BuscarPalabraEsp(Grafo g, String[] dict, char[][] tab, Cargar v1) {
        initComponents();
        this.grafo = g;
        this.diccionario = dict;
        this.tablero = tab;
        this.ventanaCargarOriginal = v1; // <--- ¡Añadir esta línea!
        this.setLocationRelativeTo(null); // Centrar la ventana (buena práctica)
        this.setResizable(false); // No permitir redimensionar (buena práctica)
        // Aquí puedes añadir más inicializaciones para tu interfaz gráfica
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
