
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import EDD.Grafo;

/**
 *
 * @author Gloria
 */

    
  public class Cargar extends javax.swing.JFrame {

    public Grafo grafo;
    public String[] diccionario;
    public char[][] tablero;

    public Cargar() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(false); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonCargarArchivo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaTablero = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDiccionario = new javax.swing.JTextArea();
        botonContinuar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("cargar sopa de letras y diccionario");

        botonCargarArchivo.setText("Cargar Archivo...");
        botonCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarArchivoActionPerformed(evt);
            }
        });

        jLabel4.setText("Tablero 4x4");

        jLabel5.setText("Diccionario:");

        textAreaTablero.setEditable(false);
        textAreaTablero.setColumns(20);
        textAreaTablero.setRows(5);
        jScrollPane1.setViewportView(textAreaTablero);

        textAreaDiccionario.setEditable(false);
        textAreaDiccionario.setColumns(20);
        textAreaDiccionario.setRows(5);
        jScrollPane2.setViewportView(textAreaDiccionario);

        botonContinuar.setText("continuar");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(botonCargarArchivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)))
                .addContainerGap(348, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(botonContinuar))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCargarArchivo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonContinuar)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarArchivoActionPerformed
       
    JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try {
                leerArchivoDeConfiguracion(archivo);
                mostrarTableroEnGUI();
                mostrarDiccionarioEnGUI();
                JOptionPane.showMessageDialog(this, "Archivo cargado exitosamente.", "Carga Completa", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage(), "Error de Archivo", JOptionPane.ERROR_MESSAGE);
                System.err.println("Error de IO al cargar archivo: " + e.getMessage());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                System.err.println("Error general al cargar archivo: " + e.getMessage()); 
               
            }
        }
    
    }//GEN-LAST:event_botonCargarArchivoActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
       
 if (grafo != null && tablero != null && diccionario != null && diccionario.length > 0) {
            this.setVisible(false);
            
            Menu menuPrincipal = new Menu(this); 
            menuPrincipal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe cargar un archivo válido antes de continuar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
            System.err.println("Error: ClassNotFoundException: " + ex.getMessage());
        } catch (InstantiationException ex) {
            System.err.println("Error: InstantiationException: " + ex.getMessage());
        } catch (IllegalAccessException ex) {
            System.err.println("Error: IllegalAccessException: " + ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("Error: UnsupportedLookAndFeelException: " + ex.getMessage());
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar().setVisible(true);
            }
        });
    }
    
                                                      


    /**
     * Lee el contenido de un archivo de texto para extraer el diccionario y el tablero.
     * Procesa las etiquetas "dic", "/dic", "tab", "/tab" para separar la información.
     * @param archivo El archivo a leer.
     * @throws IOException Si ocurre un error de lectura.
     * @throws Exception Si el formato del tablero es incorrecto.
     */
  private void leerArchivoDeConfiguracion(File archivo) throws IOException, Exception {
    BufferedReader br = null;
    String line;

    boolean inDic = false;
    boolean inTab = false;

    StringBuilder diccionarioContent = new StringBuilder();
    String tableroContentLine = null; //

    try {
        br = new BufferedReader(new FileReader(archivo));
        while ((line = br.readLine()) != null) {
            line = line.trim();

            if (line.isEmpty()) {
                continue;
            }

            System.out.println("DEBUG: Leyendo línea: [" + line + "]"); // Debug 1

            if (line.equals("dic")) {
                inDic = true;
                inTab = false;
                System.out.println("DEBUG: Entrando en sección dic.");
                continue;
            } else if (line.equals("/dic")) {
                inDic = false;
                System.out.println("DEBUG: Saliendo de sección dic.");
                continue;
            } else if (line.equals("tab")) {
                inTab = true;
                inDic = false;
                tableroContentLine = null; 
                System.out.println("DEBUG: Entrando en sección tab.");
                continue;
            } else if (line.equals("/tab")) {
                inTab = false;
                System.out.println("DEBUG: Saliendo de sección tab.");
                continue;
            }

           
            if (inDic) {
                diccionarioContent.append(line).append("\n");
            } else if (inTab) {
               
                if (tableroContentLine != null) {
                    throw new Exception("Se encontró más de una línea de tablero dentro de la sección 'tab'.");
                }
                tableroContentLine = line; 
                System.out.println("DEBUG: Contenido de tablero leido (temporal): [" + tableroContentLine + "]");
            }
        }

       
        String dicRaw = diccionarioContent.toString().trim();
        if (!dicRaw.isEmpty()) {
            String[] tempDic = new String[contarLineas(dicRaw)];
            int index = 0;
            int start = 0;
            for (int i = 0; i < dicRaw.length(); i++) {
                if (dicRaw.charAt(i) == '\n') {
                    tempDic[index++] = dicRaw.substring(start, i).trim();
                    start = i + 1;
                }
            }
            if (start < dicRaw.length()) {
                tempDic[index++] = dicRaw.substring(start).trim();
            }
            String[] finalDic = new String[index];
            for(int i = 0; i < index; i++){
                finalDic[i] = tempDic[i];
            }
            this.diccionario = finalDic;
        } else {
            this.diccionario = new String[0];
        }

        
        if (tableroContentLine == null || tableroContentLine.isEmpty()) {
            throw new Exception("La sección 'tab' del archivo no contiene datos de tablero.");
        }
        
        System.out.println("DEBUG: Llamando splitCustom con la línea final del tablero: [" + tableroContentLine + "]"); 
        String[] letrasArray = splitCustom(tableroContentLine, ','); 
        
        System.out.println("DEBUG: splitCustom devolvió " + letrasArray.length + " elementos."); 
        if (letrasArray.length > 0) {
            System.out.println("DEBUG: Primer elemento de letrasArray: [" + letrasArray[0] + "]");
        }

        int expectedSize = 16;
        int rows = 4;
        int cols = 4;

        this.tablero = new char[rows][cols];

        if (letrasArray.length != expectedSize) {
            throw new Exception("El tablero no tiene " + expectedSize + " letras (4x4). Se encontraron " + letrasArray.length + "."); 
        }

        for (int i = 0; i < expectedSize; i++) {
            if (letrasArray[i] != null && !letrasArray[i].isEmpty()) {
                this.tablero[i / cols][i % cols] = letrasArray[i].charAt(0);
            } else {
                throw new Exception("Caracter vacío o nulo encontrado en el tablero en la posición " + i + ".");
            }
        }
        
        
        construirGrafo();

    } finally {
        if (br != null) {
            br.close();
        }
    }
}

    /**
     * Implementación básica de split para String sin usar java.util.String.split().
     * Separa una cadena por un delimitador específico.
     * @param text La cadena a separar.
     * @param delimiter El carácter delimitador.
     * @return Un arreglo de cadenas resultantes.
     */
    private String[] splitCustom(String text, char delimiter) {
        int count = 0;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == delimiter) {
                count++;
            }
        }
        String[] result = new String[count + 1];
        int currentElement = 0;
        int start = 0;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == delimiter) {
                result[currentElement++] = text.substring(start, i).trim();
                start = i + 1;
            }
        }
       
        result[currentElement] = text.substring(start).trim();
        return result;
    }
    
    /**
     * Counts the number of lines in a text.
     * @param texto The text to count lines in.
     * @return The number of lines.
     */
    private int contarLineas(String texto) {
        if (texto == null || texto.isEmpty()) {
            return 0;
        }
        int count = 0;
        boolean previousCharIsNewline = true;
        for (int i = 0; i < texto.length(); i++) {
            if (texto.charAt(i) == '\n') {
                previousCharIsNewline = true;
            } else if (previousCharIsNewline) {
                count++;
                previousCharIsNewline = false;
            }
        }
        return count;
    }

    
    private void construirGrafo() {
        this.grafo = new Grafo(16);

        
        int[] dr = {-1, -1, -1, 0, 0, 1, 1, 1}; 
        int[] dc = {-1, 0, 1, -1, 1, -1, 0, 1}; 

        int rows = 4;
        int cols = 4; 

        for (int r = 0; r < rows; r++) {
            for (int c = 0; c < cols; c++) {
                int u = r * cols + c;

                for (int i = 0; i < 8; i++) { 
                    int newR = r + dr[i];
                    int newC = c + dc[i];

                   
                    if (newR >= 0 && newR < rows && newC >= 0 && newC < cols) {
                        int v = newR * cols + newC; 
                        grafo.agregarArista(u, v);
                    }
                }
            }
        }
    }

    
    private void mostrarTableroEnGUI() {
        StringBuilder sb = new StringBuilder();
        if (tablero != null) {
            for (int r = 0; r < 4; r++) {
                for (int c = 0; c < 4; c++) {
                    sb.append(tablero[r][c]).append(" ");
                }
                sb.append("\n");
            }
        }
        textAreaTablero.setText(sb.toString());
    }

    private void mostrarDiccionarioEnGUI() {
        StringBuilder sb = new StringBuilder();
        if (diccionario != null) {
            for (int i = 0; i < diccionario.length; i++) {
                if (diccionario[i] != null && !diccionario[i].isEmpty()) {
                    sb.append(diccionario[i]).append("\n");
                }
            }
        }
        textAreaDiccionario.setText(sb.toString());
        
       
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarArchivo;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaDiccionario;
    private javax.swing.JTextArea textAreaTablero;
    // End of variables declaration//GEN-END:variables
  }